name: Deploy to Rotriw Main Server
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    checkdb:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Prepare Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.8
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            -   name: Check database
                env:
                    sqlhost: ${{ secrets.DB_HOST }}
                    mysqlpassword: ${{ secrets.DB_PASSWORD }}
                run: |
                    flask db init
                    flask db check

    deploy:
        needs: checkdb
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy
                uses: appleboy/ssh-action@v0.1.10
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: |
                        cd /project/poem_snake
                        git pull
                        pip3 install -r requirements.txt
                        flask db check
                        pm2 restart poemsnake



