name: Deploy to Rotriw Main Server
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkdb
                uses: appleboy/ssh-action@v0.1.10
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: |
                        cd /project/poem_snake
                        git pull
                        flask db check
            -   name: Deploy
                uses: appleboy/ssh-action@v0.1.10
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: |
                        cd /project/poem_snake
                        pip3 install -r requirements.txt
                        pm2 restart poemsnake



